DROP TABLE LDS.DOCS;
CREATE COLUMN TABLE LDS.DOCS (
    ID NVARCHAR(100) PRIMARY KEY,
    NAME NVARCHAR(1000),
    LASTMODIFIED BIGINT,
    TYPE NVARCHAR(1000),
    STATUS NVARCHAR(100),    
    CUSTOMER NVARCHAR(100),
    CONTENT BLOB
); 

--CREATE FULLTEXT INDEX LING_FULL_INDEX ON LDS.DOCS ("CONTENT")
--CONFIGURATION 'LINGANALYSIS_FULL'
--TEXT ANALYSIS ON;


CREATE FULLTEXT INDEX TEXT_EXTRACTION ON LDS.DOCS ("CONTENT")
CONFIGURATION 'EXTRACTION_CORE_ENTERPRISE'
TEXT ANALYSIS ON
TEXT MINING ON;